### ISSUE TITLE
Require v12 KTAP support for RHEL kernel "5.15.0-201.135.6.el8uek.x86_64"

### ISSUE THREAD

**Issue by hawks2win4now** [IBM/guardium-ktap#1]
Require v12 KTAP support for RHEL 8.9 kernel of "5.15.0-201.135.6.el8uek.x86_64". KTAP fails to load at present and thus no AWS Oracle DB activity being captured into Guardium v12 Collector.

**Comment by ibm-rsubramani** [comment]
Hi @hawks2win4now,

A matching KTAP module built in July 2024 is available.  Hoiwever it appears, it is available for v11.4.  I will pass this on to our KTAP team.

Thank you for raising this issue.

**Comment by ibm-rsubramani** [comment]
Hello @hawks2win4now :  The KTAP team has asked that you open a Support ticket and they will create a module.
